package com.datiobd.spider.commons

trait Constants {
  val NAMENODE: String = "namenode"
  val PKS = "pks"
  val PATH = "path"
  val SORT_PKS = "sortPks"
  val NAME = "name"
  val SCHEMA = "schema"
  val WRITE_MODE = "writeMode"
  val FORMAT = "fileType"
  val OPTIONS = "options"
  val DEFAULT_FORMAT = "parquet"
  val DEFAULT_WRITEMODE = "overwrite"
  val PARTITION_COLUMNS = "partitionColumns"
  val CONFIG_TABLES = "tables"
  val CONFIG_APP: String = "app"
  val CONFIG_SPARK = "spark"
  val CONFIG_HDFS = "hdfs"
  val CONFIG_CONFIG = "config"
  val PROPERTIES = "properties"
  val ENABLE = "enable"
  val DEBUG = "debug"
  val TABLES = "tables"
  val INCLUDE_PARTITIONS_AS_PK = "includePartitionsAsPk"
}
